packages:
  - "apps/*"
  - "packages/*"

catalog:
  "vue": "^3.5.13"
  "vue-router": "^4.5.0"
  "@eslint/js": "^9.19.0"
  "eslint": "^9.19.0"
  "eslint-config-prettier": "^10.0.1"
  "eslint-plugin-prettier": "^5.2.3"
  "eslint-plugin-vue": "^9.32.0"
  "globals": "^15.14.0"
  "husky": "^9.1.7"
  "lint-staged": "^15.4.3"
  "typescript-eslint": "^8.23.0"
